from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class BehaviorConfig:
    """
    Configuration for Sentinel's behavior detection rules.

    Thresholds are intentionally expressed in pixel-space because
    the current system does not yet have camera calibration.

    Once homography / camera calibration is implemented, these
    can be converted to real-world units such as meters/second.
    """

    # --------------------------------------------------------------
    # Loitering
    # --------------------------------------------------------------

    loitering_enabled: bool = True
    loitering_min_duration_seconds: float = 30.0
    loitering_max_movement_px: float = 100.0
    loitering_max_speed_px_s: float = 8.0

    # --------------------------------------------------------------
    # Suspicious stop
    # --------------------------------------------------------------

    suspicious_stop_enabled: bool = True
    suspicious_stop_min_duration_seconds: float = 15.0
    suspicious_stop_max_speed_px_s: float = 3.0

    # --------------------------------------------------------------
    # Rapid movement
    # --------------------------------------------------------------

    rapid_movement_enabled: bool = True
    rapid_movement_speed_threshold_px_s: float = 180.0

    # --------------------------------------------------------------
    # Direction change
    # --------------------------------------------------------------

    direction_change_enabled: bool = True
    direction_change_angle_threshold_degrees: float = 90.0
    direction_change_min_speed_px_s: float = 10.0

    # --------------------------------------------------------------
    # Generic
    # --------------------------------------------------------------

    minimum_observations: int = 5

    def __post_init__(self) -> None:

        if self.loitering_min_duration_seconds <= 0:
            raise ValueError(
                "loitering_min_duration_seconds must be > 0"
            )

        if self.loitering_max_movement_px < 0:
            raise ValueError(
                "loitering_max_movement_px must be >= 0"
            )

        if self.loitering_max_speed_px_s < 0:
            raise ValueError(
                "loitering_max_speed_px_s must be >= 0"
            )

        if self.suspicious_stop_min_duration_seconds <= 0:
            raise ValueError(
                "suspicious_stop_min_duration_seconds must be > 0"
            )

        if self.suspicious_stop_max_speed_px_s < 0:
            raise ValueError(
                "suspicious_stop_max_speed_px_s must be >= 0"
            )

        if self.rapid_movement_speed_threshold_px_s <= 0:
            raise ValueError(
                "rapid_movement_speed_threshold_px_s must be > 0"
            )

        if not 0 < self.direction_change_angle_threshold_degrees <= 180:
            raise ValueError(
                "direction_change_angle_threshold_degrees "
                "must be between 0 and 180"
            )

        if self.minimum_observations < 2:
            raise ValueError(
                "minimum_observations must be >= 2"
            )


@dataclass(frozen=True)
class BehaviorEvent:
    """
    Normalized output generated by the behavior engine.
    """

    behavior: str
    track_id: int
    object_type: str

    severity: str
    score: int

    details: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "behavior": self.behavior,
            "track_id": self.track_id,
            "object_type": self.object_type,
            "severity": self.severity,
            "score": self.score,
            "details": self.details,
        }